### ISSUE TITLE
can not initial

### ISSUE THREAD

**Issue by B-Betty** [escnqh/OrbSlam2Test#1]
hi . i run the project, but it can not initial .i haved choosed ORBvoc.txt and Setting.yaml(the parameter is calibrated  by my own phone)

**Comment by escnqh** [comment]
你有在自己的手机上装OpenCV Manager吗

**Comment by B-Betty** [comment]
装了呀，运行安装都可以，打开app，出现图像，过一分钟左右就闪退了，一直没有初始化成功

**Comment by escnqh** [comment]
跟手机的ABI版本有关，你看一下你的手机兼容什么，然后在Application.mk文件中指定版本再编译，这个copy指令有问题需要你把生成的库文件手动复制到libs目录下再跑。

**Comment by escnqh** [comment]
如果有问题只有等我考完试寒假再看了TAT

**Comment by B-Betty** [comment]
好的，我试试

**Comment by B-Betty** [comment]
打扰一下...  想要生成libs下arm64-v8a文件夹，除了在Application.mk中的APP_ABI修改成arm64-v8a 、在Android.mk中NDK_LIBS_OUT添加arm64-v8a、app/build.gradle中abiFilters添加arm64-v8a，还需要修改哪些地方？

**Comment by escnqh** [comment]
按道理就只有这些
